const express=require("express")
const app=express()
const path=require('path')
const mongoose=require("mongoose")
const methodOverride=require("method-override")
const session=require("express-session")
const flash=require("connect-flash")
const passport=require('passport')